### ISSUE TITLE
User can name a list of Stones

### ISSUE THREAD

**Issue by Urtrope-Designs** [Urtrope-Designs/barenziah-tracker-react#3]
This can be done by simply clicking on existing name at the top of the main view after selecting the list. Doing so will turn the name into an input field and a "save" button will appear to the right(?). Clicking outside the field will "cancel" the edit. 
Name will default to "Untitled".

**Comment by scunningham777** [comment]
This might be a way to get the on-blur cancel: https://medium.com/@jessebeach/dealing-with-focus-and-blur-in-a-composite-widget-in-react-90d3c3b49a9b

**Comment by scunningham777** [comment]
Think I found a better way to do it that doesn't require race conditions or timeouts.
